### ISSUE TITLE
Technologies

### ISSUE THREAD

**Issue by AltiTorie** [AltiTorie/DremTem#1]
- Database
- API
- Website
- Mobile App
- Hardware?

**Comment by kamilagalka** [comment]
We should think about tools that aren't free to use, but have some "for students" version - I think we can use (at least some of) them, but we could ask dr Szpunar just to be sure.

**Comment by kamilagalka** [comment]
- Java
- Spring
- gRPC
- mqtt
- Arduino & Raspberry
- Kotlin
- REST
- timescale
- docker/kubernetes
